DKR1/shop/my_shop/urls.py
from django.urls import path
from . import views

app_name = 'my_shop'
urlpatterns = [
	path('',views.begin, name = 'begin'),

	path('shop',views.shop, name = 'shop'),
	path('shop/add/<int:item_id>',views.add_item, name = 'add_item'),
	path('basket',views.basket, name = 'basket'),
	path('shop/remove/<int:item_id>',views.remove_item, name = 'remove_item'),

	path('register',views.register, name = 'register'),
	path('register/create',views.create, name = 'create'),
	path('log_in',views.log_in, name = 'log_in'),
	path('log_in/check',views.check, name = 'check'),
	path('log_out',views.log_out, name = 'log_out'),
]

DKR1/shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_shop.urls'))
]

DKR1/shop/my_shop/models.py
from django.db import models

class Item(models.Model):
	name = models.CharField(max_length = 100)
	detail = models.CharField(max_length = 2000)
	price =  models.PositiveIntegerField()

	def __str__(self):
		return f'{self.name}; price = {self.price}'


class User(models.Model):
	name = models.CharField(max_length = 100)
	password = models.CharField(max_length = 100)

	def __str__(self):
		return f'{self.id}. {self.name}'

DKR1/shop/my_shop/views.py
from django.shortcuts import render
from .models import Item,User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
import redis

redis_instance = redis.StrictRedis(host=settings.REDIS_HOST,port=settings.REDIS_PORT,charset="utf-8",decode_responses=True, db=0)


# Create your views here.

def begin(request):
	return HttpResponseRedirect(reverse('my_shop:shop'))

def get_User():
	ID = redis_instance.get('id')
	if ID: 
		return User.objects.get(id = int(ID))
	else:
		return False

def get_items_in_basket():
	items = redis_instance.get('basket')
	if items:
		return items.split(',')
	else:
		return False

def set_items_in_basket(array):
	array = [str(i) for i in array]
	redis_instance.set('basket',','.join(array))

def add_item_to_basket(id):
	items = get_items_in_basket()
	if items:
		items.append(id)
	else:
		items = f'{id}'
	set_items_in_basket(items)

def delete_item_from_busket(id):
	items = get_items_in_basket()
	for i in range(len(items)):
		if items[i] == f'{id}':
			del items[i]
			break
	set_items_in_basket(items)

def full_price():
	full_pr = 0
	items = get_items_in_basket()
	if items:
		for i in items:
			temp = Item.objects.get(id=i)
			full_pr += temp.price
	return full_pr



def shop(request):
	items = Item.objects.order_by('name')
	return render(request, 'pages/shop.html',{'items': items,'login': get_User()})

def add_item(request,item_id):
	add_item_to_basket(item_id)
	return HttpResponseRedirect(reverse('my_shop:shop'))

def basket(request):
	items = get_items_in_basket()
	if items:
		basket_items = []
		for i in items:
			temp = Item.objects.get(id = i)
			basket_items.append({
				'id':temp.id,
				'name':temp.name,
				'detail':temp.detail,
				'price':temp.price,
			})
		return render(request, 'pages/basket.html',{'items': basket_items,'login': get_User(), 'full_price': full_price()})
	else:
		return render(request, 'pages/basket.html',{'items': False,'login': get_User()})

def remove_item(request,item_id):
	delete_item_from_busket(item_id)
	return HttpResponseRedirect(reverse('my_shop:basket'))






def register(request):
	return render(request, 'pages/logreg.html',{'new': True,'login': get_User()})

def create(request):
	user0 = User(
		name     = request.POST['name'    ],
		password = request.POST['password'],
	)

	user0.save()
	redis_instance.set('id', user0.id)
	return HttpResponseRedirect(reverse('my_shop:begin'))

def log_in(request):
	return render(request, 'pages/logreg.html',{'new':False,'login': get_User()})

def check(request):
	try:
		user = User.objects.get(name = request.POST['name'])
		if user.password == request.POST['password']:
			redis_instance.set('id', user.id)
			return HttpResponseRedirect(reverse('my_shop:begin'))
		else:
			return HttpResponseRedirect(reverse('my_shop:log_in'))
	except:
		return HttpResponseRedirect(reverse('my_shop:log_in'))

def log_out(request):
	redis_instance.delete('id')
	return HttpResponseRedirect(reverse('my_shop:begin'))

DKR1/shop/shop/templates/contact.html
{%extends 'mainApp/wrapper.html'%}

{%block title %} Contact {%endblock%}
{%block content %} Our contact {%endblock%}

DKR1/shop/shop/templates/global.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
</head>
<style>
body
{
    background: #2c2c2c;
}

aside{
    float: left;
    background: 181818;
    width: 20%;
    padding: 2.5%;
    height: 200vh;
    color: #fff;
    border-right: 5px solid #4d4d4d;
}

aside .logo{
    font-size: 30px;
    margin-left: 10px;
    font-weight: bold;
    position: relative;
    top: +5px

}

aside h3{
    margin-top: 40px;
    font-size: 25px
}

aside ul{list-style: none}

aside ul li{
    color: #fff;
     display: block;
     margin-top: 20px;
     transition: transform 0.6s ease;
    }
aside ul li:hover, aside ul a:hover{
    color: #eb5959;
    text-decoration: none;
    transform: scale(1.05);
}

main .features{
    float: left;
    color: #fff;
    text-align: center;
    margin-top: 100px;
    width: 75%;
    }

main .features h1{font-size: 50px}
main .features p{max-width 400px; margin: 20px auto}

.alert-warning{
    float: left;
    clear: both;
    width: 400px;
    margin: 20px 34%;
    text-align: left;
}
form{
    margin-left: 20%;
    margin-right: 20%;
    width: 500px
    margin-top: 50px
    }
    </style>
<body >
    <aside>
        <span class="logo"> {{login.name}} </span>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'my_shop:shop' %}"><li><i class="fas fa-home"></i> Главная</li></a>
            <a href="{% url 'my_shop:basket' %}"><li><i class="fas fa-shopping-basket"></i> Корзина </li></a>
            {% if login %}
            <a href="{% url 'my_shop:log_out' %}"><li><i class="fas fa-door-open"></i> Выход </li></a>
            {% else %}
            <a href="{% url 'my_shop:log_in' %}"><li><i class="fas fa-door-open"></i>Вход </li></a>
            <a href="{% url 'my_shop:register' %}"><li><i class="fas fa-newspaper"></i>Регестрация на выборы Путина  </li></a>
            {% endif %}
		    <a href="/admin">admin</a>

        </ul>
    </aside>
    <main>

        {% block content %}
        {% endblock %}

    </main>

</body>
</html>

DKR1/shop/shop/templates/pages/basket.html
{% extends 'global.html' %}

{% block content %}

<style>
	a {
		text-decoration: none;
		color: #000;
	}

	.link {
		text-decoration: underline;
		color: #00b;
	}


	.item {
		display: grid;
		grid-template-columns: auto 5em;
		grid-template-rows: 2em 3em;
		margin: 1em;
		background: #eee;
		box-shadow: 0 0 0 0 #b00;
		transition-duration: 0.2s;
	}

	.item:hover {
		box-shadow: 0 0 0 0.4em #b00;
	}

	.item > .name {
		padding: 0.5em;
		grid-column: 1 / 2;
		grid-row: 1 / 2;
		border-bottom: 1px solid #bbb;
	}

	.item > .details {
		padding: 0.5em;
		grid-column: 1 / 2;
		grid-row: 2 / 3;
	}

	.item > a {
		grid-column: 2 / 3;
		grid-row: 1 / 3;
		background: #e45e5e;
		font-size: 2em;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	 p {
		color: #ffff;
		margin: 20px;

	}

	.message {
		margin: 2em;
	}
</style>

{% if login %}
	{% if items %}
		{% for item in items %}
			<div class="item">
				<div class="name"><b>{{item.name}}</b> <font color="#0b0">{{item.price}} грн</font></div>
				<div class="details">{{item.detail}}</div>
				<a href="{% url 'my_shop:remove_item' item.id %}">-</a>
			</div>
		{% endfor %}
	<p>Сума вашої покупки складає: {{ full_price }} грн</p>
	{% else %}
	<div class="message">
		<p>Оберіть щось в <a class="link" href="{% url 'my_shop:shop' %}">Магазині</a>, і ваш вибір відобразиться тут</p>
	</div>
	{% endif %}
{% else %}
<p>Зарегайся не будь плохим человеком </p>
{% endif %}
{% endblock %}

DKR1/shop/shop/templates/pages/logreg.html
{% extends 'global.html' %}

{% block content %}

<style type="text/css">
	input, button {
		margin: 1em 1em 0em 1em;
	}

	.form {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 20em;
	}

	form {
		padding-bottom: 1em;
		background: #bbb;
	}
</style>

<div class="form">
{% if new %}
<form action="{% url 'my_shop:create' %}" method="POST">{% csrf_token %}
	<input type="text" placeholder="логін" required maxlength="100" name="name"><br>
	<input type="text" placeholder="пароль" required maxlength="100" name="password"><br>
	<button type="submit">Зареєструватись</button>
</form>
{% else %}
<form action="{% url 'my_shop:check' %}" method="POST">{% csrf_token %}
	<input type="text" placeholder="логін" required maxlength="100" name="name"><br>
	<input type="text" placeholder="пароль" required maxlength="100" name="password"><br>
	<button type="submit">Вхід</button>
</form>
{% endif %}
</div>

{% endblock %}

DKR1/shop/shop/templates/pages/shop.html
{% extends 'global.html' %}

{% block content %}

<style>
	a {
		text-decoration: none;
		color: #000;
	}

	.item {
		display: grid;
		grid-template-columns: auto 5em;
		grid-template-rows: 2em 3em;
		margin: 1em;
		background: #eee;
		box-shadow: 0 0 0 0 #0b0;
		transition-duration: 0.2s;
	}

	.item:hover {
		box-shadow: 0 0 0 0.4em #0b0;
	}

	.item > .name {
		padding: 0.5em;
		grid-column: 1 / 2;
		grid-row: 1 / 2;
		border-bottom: 1px solid #bbb;
	}

	.item > .details {
		padding: 0.5em;
		grid-column: 1 / 2;
		grid-row: 2 / 3;
	}

	.item > a {
		grid-column: 2 / 3;
		grid-row: 1 / 3;
		background: #5ee45e;
		font-size: 2em;
		display: flex;
		align-items: center;
		justify-content: center;
	}
</style>


{% if items %}
	{% for item in items %}
		<div class="item">
			<div class="name"><b>{{item.name}}</b> <font color="#090">{{item.price}} грн</font></div>
			<div class="details">{{item.detail}}</div>
			<a href="{% url 'my_shop:add_item' item.id %}">+</a>
		</div>
	{% endfor %}
{% else %}
	товари відсутні
{% endif %}

{% endblock %}